# variables
@base_url = http://127.0.0.1:8000
@token_key = {{ login.response.body.access }}

# Departamentos
GET {{base_url}}/api/apartments/ HTTP/1.1

### Detalle Departamento
GET {{base_url}}/api/apartments/1 HTTP/1.1

### Servicios
GET {{base_url}}/api/services/ HTTP/1.1

### Crear servicio
POST {{base_url}}/api/services/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token_key}}

{
  "name": "Servicio de limpieza",
  "description": "Limpieza profunda del departamento",
  "price": 50.0,
  "icon": "cleaning_icon.png"
}