# variables
@base_url = http://127.0.0.1:8000

### Crear usuario cliente
POST {{base_url}}/auth/users/ HTTP/1.1
Content-Type: application/json

{
    "username": "customer01",
    "password": "backlash-paging-lumpish"
}

# @name login
POST {{base_url}}/auth/jwt/create/ HTTP/1.1
Content-Type: application/json

{
    "username": "customer01",
    "password": "backlash-paging-lumpish"
}

### -----------------
@token_key = {{ login.response.body.access }}

### Refrescar token
POST {{base_url}}/auth/jwt/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "{{ login.response.body.access }}"
}


### Ver departamento (SIN TOKEN)
GET {{base_url}}/api/apartments HTTP/1.1


### Ver servicios (SIN TOKEN)
GET {{base_url}}/api/services HTTP/1.1


### Ver reservas (SIN TOKEN)
GET {{base_url}}/api/bookings HTTP/1.1
Authorization: Bearer {{token_key}}

### Crear reserva
POST {{base_url}}/api/bookings/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token_key}}

{
  "user_id": 1,
  "apartment_id": 1,
  "start_date": "2025-12-29",
  "end_date": "2025-12-29",
  "total_price": "900"
}


### Crear apartamento (SIN TOKEN, DEBERIA FALLAR)
POST {{base_url}}/api/apartments/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token_key}}

{
    "name": "Departamento Nuevo",
    "city": "Ciudad Nueva",
    "address": "Direccion Nueva",
    "price": "1500",
    "bedrooms": 3,
    "bathrooms": 2,
    "description": "Descripcion del departamento nuevo",
}


### Crear servicio (SIN TOKEN, DEBERIA FALLAR)
POST {{base_url}}/api/services/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token_key}}

{
    "name": "Servicio Nuevo",
    "description": "Descripcion del servicio nuevo",
    "price": "200"
}